version: '3.8'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile  
    container_name: proctoring-backend
    restart: always
    ports:
      - "8005:8005"  
    networks:
      - webnet
    env_file:
      - ./backend/.env  
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - peerjs

  frontend:
    build:
      context: ./frontend  
      dockerfile: Dockerfile
    ports:
      - "5173:5173" 
    container_name: proctoring_frontend
    volumes:
      - /usr/src/app/node_modules
    networks:
      - webnet
    depends_on:
      - backend

  peerjs:
    image: node:20-alpine
    ports:
      - "9000:9000"
    command: sh -c "npm install -g peer && peerjs --port 9000 --key peerjs --path /myapp"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge